name: gh-pages.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - website/**
      - docs/graypaper/**

permissions:
  pages: write
  id-token: write

jobs:
  build-website:
    uses: ./.github/workflows/website.yaml

  build-graypaper:
    uses: ./.github/workflows/graypaper.yaml

  combine-and-deploy:
    needs: [build-website, build-graypaper]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts/

      - name: Prepare Combined Artifact
        run: |
          # Create the directory structure
          mkdir -p combined-website

          # List all downloaded artifacts
          echo "Downloaded artifacts:"
          ls -la all-artifacts/

          # Find the website artifact (should have github-pages in the name)
          # and copy its contents to the combined website directory
          if [ -d "all-artifacts/github-pages-${{ github.run_id }}" ]; then
            cp -r all-artifacts/github-pages-${{ github.run_id }}/* combined-website/
            echo "Website files copied"
          else
            echo "Warning: Website artifact directory not found as expected"
            # Try to find it another way
            find all-artifacts -name "github-pages*" -type d | while read dir; do
              cp -r "$dir"/* combined-website/
              echo "Copied files from $dir"
            done
          fi

          # Find and copy the PDF files to the combined website directory
          if [ -d "all-artifacts/pdfs" ]; then
            cp -r all-artifacts/pdfs/* combined-website/
            echo "PDF files copied"
          else
            echo "Warning: PDF artifact directory not found"
          fi

          # List final combined website contents
          echo "Final combined website contents:"
          ls -la combined-website/

      - name: Upload Combined Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined-website

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
